### ISSUE TITLE
Easy to read definition

### ISSUE THREAD

**Issue by plenainclusion** [w3c/coga#144]
In the guide "Making Content Usable for People with Cognitive and Learning Disabilities", you mention several times "easy to read" but you do not define it and you do not explain how to make it. 
We would like to suggest you:

- Add it to the glossary
- An ISO standard about easy to read is going to be created. We encourage you to link it.

Thank you for your work.

**Comment by julierawe** [comment]
Seconding this flag about the phrase "easy to read" and suggesting some possible alternatives to avoid or clarify use of this subjective phrase:

1. Summary
"3. Help users understand with clear text and images. This includes easy words, short sentences and blocks of text, clear images, and easy to understand video"
Suggest replacing "This include easy words" with "This includes short words that don't have tricky spellings (e.g., "use" instead of "utilize")" or maybe "This includes short words that sound like they're spelled" 

3.3.1 User Story: Clear Language
“I want an easy to understand, short summary for long pieces of content or an option for an easy to read version."
Suggest replacing "easy to read version" with "version at a lower reading level"

For definition of "easy to read," suggest explaining that a lower reading level tends to have shorter sentences and shorter words that sound like they're spelled (phonetic spelling) and/or have fewer syllables (e.g., changing "utilize" to "use" will help lower the reading level)

**Comment by rachaelbradley** [comment]
Thank you for the great suggestion. We have decided to use the phrase "Easy to Understand Language" to reduce confusion. We added to the glossary with a definitoin as you suggested. We also have taken an action to speak with ISO and other organizations to discuss more standardized wording.
