### ISSUE TITLE
[Maintenance, reminder] Cycle environment variables that were encrypted with Travis

### ISSUE THREAD

**Issue by tripu** [w3c/coga#57]
[Travis CI](https://travis-ci.org/) sent a message this week alerting of a bug in the way they used to [encrypt environment variables](https://docs.travis-ci.com/user/encryption-keys/). Owners of this repo should have received it.

Depending on the way encryption was done in this repo using the Travis CLI, those values might have leaked.

This is a reminder for maintainers of this repository to make sure they discard old values, and re-encrypt new ones with the latest version of `travis`, now that the bug has been fixed.

Please close this issue if action has already been taken. Feel free to ping me or *sysreq* if you need help.

**Comment by michael-n-cooper** [comment]
I had removed the encrypted variable from the build file, and changed the key, in response to another security leak a few weeks before this one was announced. I'm not sure why this repository was nonetheless flagged for review, since my other repos on which I took the same action were not flagged, but as far as I know the issue is addressed.

**Comment by tripu** [comment]
@michael-n-cooper, perhaps in other repos you did
`travis encrypt FOO=bar`
and here
`travis encrypt FOO bar`;
the problem seems to be with that specific syntax, so I guess that's what Travis looked for to decide to which repos to send the warning&hellip;
