### ISSUE TITLE
Broken link to latest published version in the Techniques document

### ISSUE THREAD

**Issue by jfhector** [w3c/coga#88]
At the top of the Techniques document, there is a link that reads "Latest published version". That link is broken (404 error).

https://w3c.github.io/coga/techniques/

**Comment by SteveALee** [comment]
@jfhector Thank you and 'm sorry for the delay.

I'll investigate but I suspect it was not published.

**Comment by SteveALee** [comment]
See also #87

**Comment by SteveALee** [comment]
@jfhector 

That document was never published nd is redundant.

The URL https://w3c.github.io/coga/techniques/ is an auto generated preview from the source in GitHub. It's status is "Editors Draft" it indicate it's not a published version.
Due to limitations of the preview process it currently put's in a 'best guess' URL and the timestamp is 'last generated' which happens regularly.

We'll review to see if we can mark it somehow as 'never published'.

Did you find a link to the URL you gave above? Or was it just followin gthe previews form the source?

Thanks again
